inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "storage/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "Gemfile.lock"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - feature

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 50
